name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prepare environment
        run: |
          echo 'GRADLE_CACHE=./.cache/gradle/' >> $GITHUB_ENV
          echo 'GRADLE_CMD=./gradlew --no-daemon --console=plain -g $GRADLE_CACHE' >> $GITHUB_ENV
          chmod +x ./gradlew
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: ${{ env.GRADLE_CACHE }}
          key: ${{ runner.os }}-build-gradle-cache-${{ hashFiles('build.gradle') }}-${{ hashFiles('**/libraries.gradle') }}
          restore-keys: |
            ${{ runner.os }}-build-gradle-cache-
      - name: Build with Gradle
        run: $GRADLE_CMD assemble
      - name: Run the tests with Gradle
        run: $GRADLE_CMD check
      - name: Archive logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-test-reports
          path: build/reports
